### PR TITLE
Custom time point creation from normal input

### PR DESCRIPTION
**Pull request by mikx98**

### CODE REVIEW

**Comment by Siegrift** [comment]
I understood the behavior from the code, but there is no evidence about using ctrl+enter to create a time point. Is this your idea or the spec needs to be updated?

**Comment by mikx98** [comment]
It's in the spec :). Look for shortcuts in Logging mode.

**Comment by Siegrift** [comment]
In the spec its the command key, i guess that is a windows key on other keyboards right?

**Comment by hleumas** [comment]
No, it is ctrl on Windows. MAC users are using most of shortcuts with CMD instead of CTRL.

**Comment by mikx98** [comment]
Since #26 it's accepting both Mac's command key and Ctrl key.

**Pull request merged**
